def justified_print(string_value,float_value):
    print("%s:%25.2f"%(string_value.ljust(25),float_value))
emp_name=input("Enter Employee Name : ")
emp_id=int(input("Enter Employee ID : "))
basic_monthly_salary=float(input("Enter Basic Monthly Salary : "))
special_allowance=float(input("Enter Special Allowances [per month]: "))
bonus_percentage=float(input("Enter Annual Bonus Percentage : "))
monthly_gross_salary=basic_monthly_salary+special_allowance
bonus=(bonus_percentage/100)*(monthly_gross_salary*12)
annual_gross_salary=(monthly_gross_salary*12)+bonus
print("\n"+"-"*51)
print("Employee Details".center(51))
print("-"*51)
print("%s:%25s"%("Employee Name".ljust(25),emp_name))
print("%s:%25d"%("Employee ID".ljust(25),emp_id))
justified_print("Basic Monthly Salary",basic_monthly_salary)
justified_print("Special Allowances",special_allowance)
justified_print("Gross Monthly Salary",monthly_gross_salary)
justified_print("Annual Bonus",bonus)
justified_print("Annual Gross Salary",annual_gross_salary)
print("-"*51)